In [2]:
import pandas as pd
import numpy as np

In [17]:
[i*2 for i in range(5)]

[0, 2, 4, 6, 8]

In [7]:
# 先执行前面一个for循环
[i+j for i in ["a", "b"] for j in ["c", "d"]]

['ac', 'ad', 'bc', 'bd']

In [8]:
# value = a if condition else b   
# 返回值是a/b
l = [1, 2, -1, -4, 5, 0]
[1 if i >=0 else -1 for i in l]

[1, 1, -1, -1, 1, 1]

In [9]:
[(lambda x: 2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [10]:
#1.map(lambda函数， 函数参数)
#2.返回值是map对象
#3.通过list（map）  或者  [*map]转化为list对象
#4.字符串也是可以迭代的
[*map(lambda a, b: str(a)+ b, range(5), "abcd")]

['0a', '1b', '2c', '3d']

In [16]:
#list(zip("abc", "efg", "hij"))  
#zip是打包可迭代对象,因为字符串也是可以迭代的，所以可以打包字符串
list(zip(list("abc"), list("efg"), list("hij")))

[('a', 'e', 'h'), ('b', 'f', 'i'), ('c', 'g', 'j')]

In [19]:
for i, j, k in zip("abc", "efg", "hij"):
    print(i, j, k)

a e h
b f i
c g j


In [22]:
for index, value in enumerate(list("abc", "efg", "hij")):
    print(index, value)

TypeError: list expected at most 1 arguments, got 3

In [35]:
print(list(("a","b","c")))
list("abc")

['a', 'b', 'c']


['a', 'b', 'c']

In [34]:
print(list(i for i in range(5)))
list("12345")

[0, 1, 2, 3, 4]


['1', '2', '3', '4', '5']

In [38]:
for index, value in enumerate(list(("abc", "efg", "hij"))):
    print(index, value)

0 abc
1 efg
2 hij


In [60]:
zipped = zip("abc", "def", "hij")

In [64]:
zipped = [*zipped]
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [63]:
[*zip(*zipped)]

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

In [67]:
np.arange(1, 10, 4)

array([1, 5, 9])

In [21]:
# eye默认是方阵，3表示(3, 3)
print(np.eye(3), end = "\n\n")
# 直接传入维度range大小，不可以传入元组表示维度
print(np.eye(3, 2))
np.eye((3,2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0.]
 [0. 1.]
 [0. 0.]]


TypeError: 'tuple' object cannot be interpreted as an integer

In [22]:
# 3表示元组(3,1),同理 ones和zeros
print(np.zeros(3), end = "\n\n")
# 传入必须是元组
print(np.zeros((4, 3)))
np.zeros(4,3)


[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


TypeError: data type not understood

In [34]:
# 注意概率和为1
np.random.choice(list("abcde"), 2, replace = True, p = [0.3, 0.1 ,0.4, 0.1, 0.1])

array(['c', 'a'], dtype='<U1')

In [27]:
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

array(['b', 'c'], dtype='<U1')

In [36]:
np.random.rand(3)

array([0.67715265, 0.05506902, 0.73103771])

In [37]:
np.random.rand(3, 4)

array([[0.0397927 , 0.65221182, 0.84638775, 0.65651394],
       [0.52169761, 0.98830848, 0.8358711 , 0.89169734],
       [0.87843598, 0.17782988, 0.03466274, 0.60351854]])

In [41]:
np.arange(3)
t

array([0, 1, 2])