In [2]:
import pandas as pd
import numpy as np

In [17]:
[i*2 for i in range(5)]

[0, 2, 4, 6, 8]

In [7]:
# 先执行前面一个for循环
[i+j for i in ["a", "b"] for j in ["c", "d"]]

['ac', 'ad', 'bc', 'bd']

In [8]:
# value = a if condition else b   
# 返回值是a/b
l = [1, 2, -1, -4, 5, 0]
[1 if i >=0 else -1 for i in l]

[1, 1, -1, -1, 1, 1]

In [9]:
[(lambda x: 2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [10]:
#1.map(lambda函数， 函数参数)
#2.返回值是map对象
#3.通过list（map）  或者  [*map]转化为list对象
#4.字符串也是可以迭代的
[*map(lambda a, b: str(a)+ b, range(5), "abcd")]

['0a', '1b', '2c', '3d']

In [16]:
#list(zip("abc", "efg", "hij"))  
#zip是打包可迭代对象,因为字符串也是可以迭代的，所以可以打包字符串
list(zip(list("abc"), list("efg"), list("hij")))

[('a', 'e', 'h'), ('b', 'f', 'i'), ('c', 'g', 'j')]

In [19]:
for i, j, k in zip("abc", "efg", "hij"):
    print(i, j, k)

a e h
b f i
c g j


In [22]:
for index, value in enumerate(list("abc", "efg", "hij")):
    print(index, value)

TypeError: list expected at most 1 arguments, got 3

In [35]:
print(list(("a","b","c")))
list("abc")

['a', 'b', 'c']


['a', 'b', 'c']

In [34]:
print(list(i for i in range(5)))
list("12345")

[0, 1, 2, 3, 4]


['1', '2', '3', '4', '5']

In [38]:
for index, value in enumerate(list(("abc", "efg", "hij"))):
    print(index, value)

0 abc
1 efg
2 hij


In [60]:
zipped = zip("abc", "def", "hij")

In [64]:
zipped = [*zipped]
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [63]:
[*zip(*zipped)]

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

In [102]:
import numpy as np  
a1 = np.array([[1,2,3,4],[5,6,7,8]])  
print(a1)  
print("数据类型",type(a1))           #打印数组数据类型  
print("数组元素数据类型：",a1.dtype) #打印数组元素数据类型  
print("数组元素总数：",a1.size)      #打印数组尺寸，即数组元素总数  
print("数组形状：",a1.shape)         #打印数组形状  
print("数组的维度数目",a1.ndim)      #打印数组的维度数目  

[[1 2 3 4]
 [5 6 7 8]]
数据类型 <class 'numpy.ndarray'>
数组元素数据类型： int32
数组元素总数： 8
数组形状： (2, 4)
数组的维度数目 2


In [67]:
np.arange(1, 10, 4)

array([1, 5, 9])

In [21]:
# eye默认是方阵，3表示(3, 3)
print(np.eye(3), end = "\n\n")
# 直接传入维度range大小，不可以传入元组表示维度
print(np.eye(3, 2))
np.eye((3,2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0.]
 [0. 1.]
 [0. 0.]]


TypeError: 'tuple' object cannot be interpreted as an integer

In [22]:
# 3表示元组(3,1),同理 ones和zeros
print(np.zeros(3), end = "\n\n")
# 传入必须是元组
print(np.zeros((4, 3)))
np.zeros(4,3)


[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


TypeError: data type not understood

In [34]:
# 注意概率和为1
np.random.choice(list("abcde"), 2, replace = True, p = [0.3, 0.1 ,0.4, 0.1, 0.1])

array(['c', 'a'], dtype='<U1')

In [27]:
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

array(['b', 'c'], dtype='<U1')

In [36]:
np.random.rand(3)

array([0.67715265, 0.05506902, 0.73103771])

In [37]:
np.random.rand(3, 4)

array([[0.0397927 , 0.65221182, 0.84638775, 0.65651394],
       [0.52169761, 0.98830848, 0.8358711 , 0.89169734],
       [0.87843598, 0.17782988, 0.03466274, 0.60351854]])

In [41]:
np.arange(3)
t

array([0, 1, 2])

In [5]:
t = np.array([[1, 2], [3, 4]])
t

array([[1, 2],
       [3, 4]])

In [7]:
t.reshape(-1, order = "F")

array([1, 3, 2, 4])

In [18]:
t = np.arange(9).reshape(3, 3)
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
t = t[np.ix_([False, False ,True], [True, False ,False])]
t.reshape(-1)

array([6])

In [28]:
t = np.arange(8)
print(t)
print(t.nonzero(), np.nonzero(t))
print(t.argmax(), np.argmax(t))

[0 1 2 3 4 5 6 7]
(array([1, 2, 3, 4, 5, 6, 7], dtype=int64),) (array([1, 2, 3, 4, 5, 6, 7], dtype=int64),)
7 7


In [34]:
print(t.any())
np.any(t)

True


True

In [33]:
print(np.all(t))
print(t.all())

False
False


In [42]:
t = np.array([4, 7, 2 ,5])
print(t.cumprod(), t.cumsum(), np.diff(t))
#cumprod和cumsum是累计结果，但是diff只是前者和后者之差，没有累计结果

[  4  28  56 280] [ 4 11 13 18] [ 3 -5  3]


In [41]:
t.diff()#diff只能用在np上

AttributeError: 'numpy.ndarray' object has no attribute 'diff'

In [109]:
t = np.array([4, 7, 2 ,5, 9])
t

array([4, 7, 2, 5, 9])

In [110]:
print(t.mean())
t.sum() / t.shape[0]

5.4


5.4

In [111]:
print(np.quantile(t, 0.5))
np.median(t)

5.0


5.0

In [84]:
t.median()#只能用在np上，array不可用

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [123]:
# np.median(x) = np.quantile(x, 0.5)
t = np.array([4, 7, 2 ,5])
print(t.mean(), np.median(t), np.quantile(t, 0.5))

4.5 4.5 4.5


样本标准差=sqrt(((x1-x)^2 +(x2-x)^2 +......(xn-x)^2)/（n-1）)<br/>
总体标准差=sqrt(((x1-x)^2 +(x2-x)^2 +......(xn-x)^2)/n )<br/>
样本方差=((x1-x)^2 +(x2-x)^2 +......(xn-x)^2)/（n-1）<br/>
样本标准差=((x1-x)^2 +(x2-x)^2 +......(xn-x)^2)/n <br/>
**总体方差分母为N， 样本方差分母为N-1**

极差:max(data)-min(data)<br>
总体方差:np.var()、nanvar()<br>
样本方差:np.var(ddof=1)<br>
总体标准差:np.std()<br>
样本标准差:np.std(ddof=1)<br>
标准差系数:np.std(ddof=1)/np.mean()

In [77]:
t = np.array([4, 7, 2 ,5, 9])
t

array([4, 7, 2, 5, 9])

In [86]:
print(t.var(ddof = 1))
print(((t - t.mean())**2).sum() / (t.shape[0] - 1))

4.333333333333333
4.333333333333333


In [87]:
print(t.var())
print(((t - t.mean())**2).sum() / (t.shape[0]))

3.25
3.25


In [75]:
print(t.std(ddof = 1))
print(np.sqrt(((t - t.mean())**2).sum() / (t.shape[0] - 1)))

2.701851217221259
2.701851217221259


In [76]:
print(t.std())
print(np.sqrt(((t - t.mean())**2).sum() / (t.shape[0])))

2.4166091947189146
2.4166091947189146


In [137]:
x = np.ones(3)
y = np.ones((2, 1))
x + y #(1, 3) 和 (2, 1)

array([[2., 2., 2.],
       [2., 2., 2.]])

In [138]:
x = np.ones(3)
y = np.ones((2, 3))
x + y #(1, 3) 和 (2, 3)

array([[2., 2., 2.],
       [2., 2., 2.]])

In [140]:
x = np.ones(3)
y = np.ones((2, 2))
x + y #(1, 3) 和 (2, 2)

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

![](./np.linalg.norm.png)

In [39]:
np.arange(4).reshape(2, 2)

array([[0, 1],
       [2, 3]])

In [46]:
data = np.arange(4).reshape(2, 2)
print(np.linalg.norm(data))
print(np.linalg.norm(data, ord = 2))
print(np.sqrt((data**2).sum()))

3.7416573867739413
3.702459173643833
3.7416573867739413


In [27]:
data = np.arange(4).reshape(2, 2)
print(np.linalg.norm(data, ord = 1))
print(abs(data).sum())

4.0
6


In [28]:
np.linalg.norm(data, ord = np.inf)

5.0

In [38]:
# 一维数据， 二范式及 ord = np.inf
data = np.arange(4)
print("二范式：")
print(np.linalg.norm(data))# 默认二范式
print(np.linalg.norm(data, ord = 2))
print(np.sqrt((data**2).sum()))
print("np.inf：")
print(np.linalg.norm(data, ord = np.inf))
print(np.max(abs(data)))

二范式：
3.7416573867739413
3.7416573867739413
3.7416573867739413
np.inf：
3.0
3


In [33]:
# 一维数据， 一范式
data = np.arange(4)
print(np.linalg.norm(data, ord = 1))
print(abs(data).sum())

6.0
6


In [42]:
np.random.rand(2, 3)

array([[0.53724839, 0.78546692, 0.93567221],
       [0.07801946, 0.51068348, 0.71319568]])

In [44]:
np.empty((3, 4))

array([[8.47765619e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [6.23053953e-307, 2.83435762e-032, 1.16301788e+165,
        3.75872558e+179],
       [3.73608865e-061, 6.17021482e-042, 1.08645971e-071,
        4.11832800e-033]])

# 作业1

In [115]:
M1 = np.arange(6).reshape(2, 3)# (2, 3)
M2 = np.arange(6, 6 + 12).reshape(3, 4)# (3, 4)
M3 = np.empty((M1.shape[0], M2.shape[1]))# (2, 4)

In [123]:
[   [   sum(   [M1[i][ k] * M2[k][j]  for k in range(M1.shape[1]) ])  for j in range(M2.shape[1])]  for i in range(M1.shape[0])]

[[38, 41, 44, 47], [128, 140, 152, 164]]

In [124]:
M1@M2

array([[ 38,  41,  44,  47],
       [128, 140, 152, 164]])

In [106]:
# 列表推导式：一个表达式，后面跟一个 for 子句，然后是零个或多个 for或 if 子句。 
[(i,j) for i in [1,2,3] for j in [1,2,3] if i !=j]

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]

问题1：将矩阵的行列反转

In [103]:
mat = np.arange(3 * 4).reshape(3, 4)
transposed = []
for i in range(4):
    transposed.append([row[i] for row in mat])
print(mat)
print(transposed)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0, 4, 8], [1, 5, 9], [2, 6, 10], [3, 7, 11]]


上述写法等价于以下双层for循环

In [102]:
mat = np.arange(3 * 4).reshape(3, 4)
trans = []
for j in range(mat.shape[1]):
    temp = []
    for row in mat:
        temp.append(row[j])
    trans.append(temp)
print(mat, trans, sep = "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0, 4, 8], [1, 5, 9], [2, 6, 10], [3, 7, 11]]


上述写发等价于以下列表推导式的嵌套

In [105]:
mat = np.arange(3 * 4).reshape(3, 4)
trans = [[row[i] for row in mat] for i in range(mat.shape[1])]
print(mat ,trans, sep = '\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0, 4, 8], [1, 5, 9], [2, 6, 10], [3, 7, 11]]


问题2： 求矩阵每行的和，用列表推导式

In [141]:
data = np.arange(1, 1 + 12).reshape(3, 4)
print(data)
[sum([data[i][k] for k in range(data.shape[1])]) 
                         for i in range(data.shape[0])]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[10, 26, 42]

# 作业2

In [154]:
A = np.arange(1,10).reshape(3,-1)
B = A * (1 / A).sum(1)
print(A, B, sep = "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.83333333  1.23333333  1.13690476]
 [ 7.33333333  3.08333333  2.27380952]
 [12.83333333  4.93333333  3.41071429]]


# 作业3

In [180]:
np.random.seed(0)
m, n ,p = 100, 80, 50
b = np.random.randint(0, 2, (m, p))
u = np.random.randint(0, 2, (p, n))
z = np.random.randint(0, 2, (m, n))

In [186]:
sums = []
for i in range(z.shape[0]):
    for j in range(z.shape[1]):
        sums.append(np.sum((b[i] - u.T[j])**2) * z[i][j])
np.sum(sums)

100566